### ISSUE TITLE
Stop IDs

### ISSUE THREAD

**Issue by yspreen** [jamespfennell/path-train-gtfs-realtime#11]
Since the link to the "official GTFS data" is dead and leads to a 404, I went with the next best option which was https://mobilitydatabase.org/feeds/mdb-517

There I get a list of the stops below.

The rt feed from this project instead produces stops like F20S, F21S, F22S, F23S, F24S, F25S, F26S, F27S, F27N, F26N, F25N, F24N, F23N, F22N, F21N, F20N, A42N, G36N, G35N, G34N, G33N, G32N, G31N, G30N, G29N, G28N, G26N, G24N, G22N

Which seems like a completely different system. Since the official data is compatible with a set of directions as well, I'd love to be able to use that one if possible. Is there a mapping?

Official stops:  
26722
26723
26724
26725
26726
26727
26728
26729
26730
26731
26732
26733
26734
4249031
781715
781716
781717
781718
781719
781720
781721
781722
781723
781724
781725
781726
781727
781728
781729
781730
781731
781732
781733
781734
781735
781736
781737
781738
781739
781740
781741
781763
782490
782491
782492
782493
782494
782496
782497
782498
782499
782500
782501
782503
782504
782505
782506
782507
782508
782509
782510
782511
782512
794724

**Comment by jamespfennell** [comment]
Thanks for the report! It seems like the direct GTFS static link still works: http://data.trilliumtransit.com/gtfs/path-nj-us/path-nj-us.zip I'll fix the README to point to this file instead of the zombie Port Authority website.

I don't think the realtime feed is returning stop IDs like `F20S` - those actually look like the stop IDs used by the NYC subway. The realtime feed here uses the stop IDs referenced in this code: https://github.com/jamespfennell/path-train-gtfs-realtime/blob/master/gtfsmapping.go#L9-L21 So 26722 etc. I've checked my production instance and everything looks fine...

**Comment by yspreen** [comment]
Hmm I must’ve run this against the wrong stream. My bad! Will double check

**Comment by yspreen** [comment]
You're of course absolutely right. I forked my mta service and forgot to replace the URL. Solved! Apologies for not coming up with this error myself, coding late at night is never a great idea 😄

**Comment by jamespfennell** [comment]
Hehe, all good, glad it worked!
